### ISSUE TITLE
[libretro] Downsampling + CRT shaders not working properly.

### ISSUE THREAD

**Issue by n1ghttrap** [stenzek/duckstation#2229]
I started a Swanstation thread about the issue here:  https://github.com/libretro/swanstation/issues/7
However, I've recently gathered that this is the active and officially supported Duckstation core, and the issue is present here as well.  CRT shaders, such as Royale will act correctly at 1x rendering scale, but will break and exhibit completely subdued effects and uneven scanlines when you downsample.  The ideal output would be for the shader to be applied to a "1x", post-downsampled image so you get even, correct scanlines and all the other proper effects combined with the antialiasing.  Pictures for comparison's sake are in the above thread.  This works in Beetle HW and Mupen64plus, for reference.  CRT shading + downsampling provides a pleasantly jaggy free, low resolution image, and it would be nice if it worked.  Thanks in advance.

**Comment by stenzek** [comment]
Have you tried with Vulkan or GL? This might be a D3D issue, duckstation is one of the few (only?) cores which use D3D by default.

**Comment by stenzek** [comment]
This should be fixed in the latest builds on duckstation.org, and it looks like the libretro buildbot has picked it up as well.

**Comment by n1ghttrap** [comment]
Same results in Vulkan, OGL, and D3D: correct at 1x rendering regardless of downsampling setting (since it needs be rendered at a higher resolution to work anyway), the shader's broken when rendering scale is multiplied (which is expected), but still broken in when you turn downsampling on.
![Silent Hill (USA)-210606-105436](https://user-images.githubusercontent.com/30274474/120931189-2f02eb00-c6b6-11eb-89e9-a2a376bbbc5d.jpg)
![Silent Hill (USA)-210606-105501](https://user-images.githubusercontent.com/30274474/120931191-2f9b8180-c6b6-11eb-8c7f-81a5e7a970c5.jpg)

**Comment by stenzek** [comment]
Did you update to the latest build? The scan lines are visible for me now with downsampling on.

**Comment by n1ghttrap** [comment]
> Did you update to the latest build? The scan lines are visible for me now with downsampling on.

Yes, downloaded from Retroarch just a moment ago.  What multiplier are you using in combination with downsampling?

**Comment by stenzek** [comment]
I was using 5x. Try the duckstation.org/libretro link, or post the log.

**Comment by n1ghttrap** [comment]
Works with the duckstation.org/libretro one.  Awesome, thanks a lot.  I'm gonna try the downloaded one again just to be sure I didn't need to jiggle the settings a bit.
![Silent Hill (USA)-210606-110937](https://user-images.githubusercontent.com/30274474/120931618-ff54e280-c6b7-11eb-910f-b17ad14fb30f.jpg)

**Comment by stenzek** [comment]
I guess it hasn't updated the buildbot download yet, then. Should happen soon enough.

**Comment by n1ghttrap** [comment]
Yeah, overwrote from their server and back to square one.  Hopefully soon, though.  Thanks again.

**Comment by stenzek** [comment]
Yeah, not sure what schedule it operates on, it's out of my control.
